defaults:
  - _self_
  - embedding_sizes

seed: 42
group: "MIL_NTU"
infdatasetpath: "/home/gul075/MOE_github/MOE/data/leukemia/AML_APL/Inference/Patch40xNorm"
featfolder: "/n/data2/hms/dbmi/kyu/lab/gul075"

data:
  cohort: "NTU"
  k_fold: true
  folds: 5
  folds_base_dir: "data/leukemia/AML_APL/NTU/Patch40xNorm"
  n_patches: 950
  batch_size: 32
  magnification: 40
  random_selection:
    train: true
    val: true
  feat_folder: "/n/data2/hms/dbmi/kyu/lab/gul075/Cytology_Feature_NTU_40x_Norm"
  wsi_type: "permanent"
  n_classes: 2
  num_workers: 16

moe:
  selected_experts:
    - uni
    - gigapath
    - lunit
  expert_heads:
    - _target_: models.owkin.abmil.ABMIL
      in_features: ${EMBEDDING_SIZES.${moe.selected_experts.0}}
      out_features: ${data.n_classes}
      metadata_cols: 0
    - _target_: models.owkin.abmil.ABMIL
      in_features: ${EMBEDDING_SIZES.${moe.selected_experts.1}}
      out_features: ${data.n_classes}
      metadata_cols: 0
    - _target_: models.owkin.abmil.ABMIL
      in_features: ${EMBEDDING_SIZES.${moe.selected_experts.1}}
      out_features: ${data.n_classes}
      metadata_cols: 0
  router:
    _target_: models.owkin.abmil.ABMIL
    in_features: -1
    out_features: -1
    metadata_cols: 0
  drop_p: 0.1
  router_temperature: 1.0
  moe_temperature: 1.0
  strategy: "weighted_sum"

optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  weight_decay: 1e-4

criterion:
  _target_: torch.nn.CrossEntropyLoss

train:
  epochs: 1000
  early_stopping: true
  patience: 900
  early_stopping_metric: "auc_pr"
  best_metric: "auc_pr"
  device: "cpu" 
  lambda_entropy: 0.0
  lambda_balance: 0.5
  z_loss_scale: 0.1

checkpoints:
  save_dir: "/n/scratch/users/g/gul075/checkpoints/Leukemia/AML_APL2_CLIPPED/NTU/40xNORM"

logger:
  _target_: utils.logger.TensorboardLogger
  log_dir: "/n/scratch/users/g/gul075/TBLOGS_AMLAPL_CLIPPED"
  experiment_id: "${now:%Y-%m-%d_%H-%M-%S}_leukemia_AMLAPL_mil_UNIGIGALUNIT_NTU_40xNorm"

